2015-01-20 14:16:00,000 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,207 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,273 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,693 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,728 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,754 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,836 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,971 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:00,994 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,004 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,004 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,016 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,043 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,064 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,071 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,094 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 14:16:01,094 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1251)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1252)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1253)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1254)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1255)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1256)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1257)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1258)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1259)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1260)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1261)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1262)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1263)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1264)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1265)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1266)
[2015-01-20 15:31:14 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1267)
2015-01-20 15:31:15,544 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:15,555 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:15,611 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:15,669 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:15,825 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:15,860 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:15,960 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,048 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,111 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,120 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,152 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,160 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,178 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,199 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,226 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,234 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 15:31:16,254 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
[2015-01-20 17:01:33 -0700] [1247] [CRITICAL] WORKER TIMEOUT (pid:1467)
2015-01-20 17:01:36,263 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:01,311 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:01,375 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:01,410 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:01,623 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:01,900 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:01,993 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,058 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,142 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,173 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,212 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,269 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,273 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,309 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,342 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,366 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,399 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:01:02,419 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:05:43,187 Exception on /css/custom.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: css/custom.css
2015-01-20 23:05:43,186 Exception on /css/bootstrap.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: css/bootstrap.css
2015-01-20 23:05:43,194 Exception on /js/CStask.js [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: js/CStask.js
2015-01-20 23:05:43,202 Exception on /img/f_key.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: img/f_key.png
2015-01-20 23:05:43,211 Exception on /img/j_key.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: img/j_key.png
2015-01-20 23:05:46,700 Exception on /css/bootstrap.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: css/bootstrap.css
2015-01-20 23:05:46,700 Exception on /css/custom.css [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: css/custom.css
2015-01-20 23:09:46,212 Exception on /img/f_key.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: img/f_key.png
2015-01-20 23:09:46,212 Exception on /img/j_key.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: img/j_key.png
2015-01-20 23:09:48,539 Exception on /img/f_key.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: img/f_key.png
2015-01-20 23:09:48,539 Exception on /img/j_key.png [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 666, in regularpage
    return render_template(foldername+"/"+pagename)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 127, in render_template
    return _render(ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 830, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "/usr/local/lib/python2.7/site-packages/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 64, in get_source
    raise TemplateNotFound(template)
TemplateNotFound: img/j_key.png
2015-01-20 23:11:13,303 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,309 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,313 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,313 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,344 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,352 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,360 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,365 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,377 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,394 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,395 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,397 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,408 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,408 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,408 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,412 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-20 23:11:13,413 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,115 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,115 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,172 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,455 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,700 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,743 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,847 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,935 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,968 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:32,989 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:33,017 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:33,024 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:33,041 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:33,062 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:33,093 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:33,121 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 18:57:33,135 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:06,710 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:06,726 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:06,742 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:06,988 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,246 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,384 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,435 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,542 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,552 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,612 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,637 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,642 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,647 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,670 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,675 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,702 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:14:07,729 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:20:49,979 Exception on /consent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/user_utils.py", line 15, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 309, in give_consent
    consent_string = insert_mode(consent_string, mode)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 645, in insert_mode
    new_html = page_html[:match.end()] + "&mode=" + mode +\
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1141: ordinal not in range(128)
2015-01-21 19:20:58,047 Exception on /consent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/user_utils.py", line 15, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 309, in give_consent
    consent_string = insert_mode(consent_string, mode)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 645, in insert_mode
    new_html = page_html[:match.end()] + "&mode=" + mode +\
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1141: ordinal not in range(128)
2015-01-21 19:21:11,463 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,470 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,473 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,476 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,479 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,479 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,479 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,482 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,482 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,485 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,488 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,488 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,491 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,494 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,495 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,496 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:11,502 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:20,180 Exception on /consent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/user_utils.py", line 15, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 309, in give_consent
    consent_string = insert_mode(consent_string, mode)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 645, in insert_mode
    new_html = page_html[:match.end()] + "&mode=" + mode +\
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1141: ordinal not in range(128)
2015-01-21 19:21:31,509 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:31,628 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:31,662 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:31,820 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:31,876 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,036 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,177 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,248 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,289 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,354 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,375 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,413 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,449 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,452 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,464 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,470 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:32,499 /usr/local/lib/python2.7/site-packages/psiturk/psiturk_js/psiturk.js
2015-01-21 19:21:35,158 Exception on /consent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/user_utils.py", line 15, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 309, in give_consent
    consent_string = insert_mode(consent_string, mode)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 645, in insert_mode
    new_html = page_html[:match.end()] + "&mode=" + mode +\
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1141: ordinal not in range(128)
2015-01-21 19:22:54,173 Exception on /consent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/user_utils.py", line 15, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 309, in give_consent
    consent_string = insert_mode(consent_string, mode)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 645, in insert_mode
    new_html = page_html[:match.end()] + "&mode=" + mode +\
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1141: ordinal not in range(128)
2015-01-21 19:23:06,844 Exception on /consent [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/psiturk/user_utils.py", line 15, in new_func
    resp = make_response(func(*args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 309, in give_consent
    consent_string = insert_mode(consent_string, mode)
  File "/usr/local/lib/python2.7/site-packages/psiturk/experiment.py", line 645, in insert_mode
    new_html = page_html[:match.end()] + "&mode=" + mode +\
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1141: ordinal not in range(128)
